version: "2.1"

services:
  php-cli:
    image: exozet/php-fpm:7.1.2-sudo
    user: www-data
    entrypoint: bash
    volumes:
      - ./:/usr/src/app
      - ./.docker/cache/composer:/composer/cache/
    depends_on:
      - nginx
  php-fpm:
    image: exozet/php-fpm:7.1.2
    volumes_from:
      - lsyncd
  nginx:
    image: nginx:1.11.10
    depends_on:
      - php-fpm
    ports:
      - "8080:8080"
    volumes:
      - ./:/usr/src/app
      - ./.docker/nginx.conf:/etc/nginx/conf.d/default.conf
  lsyncd:
    image: dracoblue/lsyncd
    environment:
    - SOURCES=/mnt/vendor
    - DESTINATIONS=/usr/src/app/vendor
    - EXCLUDES=.svn:.git:.docker
    volumes:
      - ./:/usr/src/app
      - ./vendor:/mnt/vendor
      - /usr/src/app/vendor